apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "fruits-ui.serviceAccountName" . }}
  labels:
    {{- include "fruits-ui.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- if .Values.dockercfg }}
imagePullSecrets:
  - name: {{ include "app.fullname" . }}-dockercfg
{{- end }}