apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fruits-ui.fullname" . }}
  labels:
    {{- include "fruits-ui.labels" . | nindent 4 }}
data:
  {{- if .Values.fruitsApiURL }}
  FRUITS_API_URI: {{ .Values.fruitsApiURL }}
  {{- end }}