trigger:
  name: dockerhub
  identifier: dockerhub
  enabled: true
  orgIdentifier: default
  projectIdentifier: googleclouddemos
  pipelineIdentifier: fruitsui
  source:
    type: Artifact
    spec:
      type: DockerRegistry
      spec:
        connectorRef: DockerHub
        imagePath: kameshsampath/fruits-ui
        tag: <+trigger.artifact.build>
  inputYaml: |
    pipeline:
      identifier: fruitsui
      stages:
        - stage:
            identifier: Deploy_to_Kube
            type: Deployment
            spec:
              service:
                serviceInputs:
                  serviceDefinition:
                    type: NativeHelm
                    spec:
                      manifests:
                        - manifest:
                            identifier: fruits-ui-helm
                            type: HelmChart
                            spec:
                              chartVersion: 0.0.1
                      artifacts:
                        primary:
                          primaryArtifactRef: Primary
                          sources:
                            - identifier: Primary
                              type: DockerRegistry
                              spec:
                                imagePath: kameshsampath/fruits-ui
                                tag: <+trigger.artifact.build>
              environment:
                infrastructureDefinitions:
                  - identifier: GKE
                    inputs:
                      identifier: GKE
                      type: KubernetesGcp
                      spec:
                        namespace: fruits-app
