apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fruits-api.dbConnectionSecret" .}}
  labels:
    {{- include "fruits-api.labels" . | nindent 4 }}
data:
{{- range .Values.mongoDBConnectionParams }}
  {{ .name | quote }}: {{ .value  | b64enc | quote  }}
{{- end }}
{{- range .Values.dbConnectionParams }}
  {{ .name | quote }}: {{ .value  | b64enc | quote  }}
{{- end }}