{{- if .Values.dockercfg }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app.fullname" . }}-dockercfg
  annotations:
    harness.io/skip-versioning: "true"
data:
  .dockercfg: |-
    {{ .Values.dockercfg }}
type: kubernetes.io/dockercfg
{{- end }}